# Generated by Django 3.0.7 on 2020-06-11 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pais',
            options={'verbose_name_plural': 'paises'},
        ),
        migrations.AddField(
            model_name='pais',
            name='codigo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
