# Generated by Django 3.0.7 on 2020-06-12 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0002_auto_20200611_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pais',
            name='id',
        ),
        migrations.AlterField(
            model_name='pais',
            name='codigo',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
